project:
  type: website


website:
  title: "AnAnt Patel"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog.qmd
        text: Blogs
      - text: Works
        menu: 
          - text: Student File System
            url: https://github.com/anant0301/student-file-system
          - text: Hierarchical SCLs
            url: https://github.com/anant0301/hierarchical-scl

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



